# Generated by Django 4.2.1 on 2023-06-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                ("Eid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("username", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=20)),
            ],
        ),
    ]
