# Generated by Django 4.2.1 on 2023-06-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="desc",
            field=models.TextField(default=""),
        ),
    ]
