# Generated by Django 4.2.1 on 2023-06-04 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_customuser_alter_task_user_delete_entity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="name",
        ),
    ]
